######################################################################################################
# 
# Here you can configure the rules for the proxy.
# This example is configuration of sharding rule.
#   
# If you want to use sharding, please refer to this file; 
# if you want to use master-slave, please refer to the config-master_slave.yaml.
# 
######################################################################################################

#schemaName: sharding_db
#
dataSources:
  single_source:
    url: jdbc:mysql://172.16.4.42:3306/contract_shard?serverTimezone=UTC&useSSL=false
    username: root
    password: yZT0b6m32UDg
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50


shardingRule:
  tables:
    t_order:
      actualDataNodes: single_source.loan_transfer_contract_${0..127}
      tableStrategy:
        inline:
          shardingColumn: loan_transfer_id
          algorithmExpression: loan_transfer_contract_${loan_transfer_id % 128}
  bindingTables:
  - loan_transfer_contract
#  defaultDatabaseStrategy:
#    inline:
#      shardingColumn: user_id
#      algorithmExpression: ds_${user_id % 2}
#  defaultTableStrategy:
#    inline:
#      shardingColumn: loan_transfer_id
#      algorithmExpression: loan_transfer_contract_${loan_transfer_id % 128}
#    none:
#  defaultKeyGeneratorClassName: io.shardingsphere.core.keygen.DefaultKeyGenerator
